新增申请当日离校
Dr-TSNG/HIT-clock pull request #16
Opened 2021-09-18 16:19 UTC by ic-liuwei

当日离校申请，新增一个action

2021-09-18 23:08 UTC, Dr-TSNG requested changes
commit 有点乱，你整理下，顺便记得先合并上游

2021-09-18 23:08 UTC, Dr-TSNG commented on .github/workflows/main.yml
> +        pip install pytz
main 文件好像没必要改

2021-09-18 23:08 UTC, Dr-TSNG commented on .github/workflows/leave.yml
> +      run: python leave_school_1.py
整理一下 commit，为啥有个 leave 还有个 leave_1

2021-09-18 23:08 UTC, Dr-TSNG commented on 每日上报.py
> +# 		driver.execute_script('document.getElementById("kzl18-0").click()')
记得合并一下上游

2021-09-20 02:26 UTC, Dr-TSNG commented
将 每日上报.py 改成和 master 一样，不然不能 squash merge

2021-09-20 05:13 UTC, ic-liuwei commented
好了好了，昨天出校申请有点问题，用的xpath不太稳定

2021-09-20 05:22 UTC, merged