完成自动申请出校功能
Dr-TSNG/HIT-clock pull request #46
Opened 2022-09-26 15:22 UTC by 0x401000Nu1l

更改了workflow，先申请后出校

2022-09-27 04:55 UTC, Dr-TSNG commented
两个 workflow 最好分开，因为不是所有人都要申请出校，另外 schedule 不要改，这是 UTC 时间不是本地时间

2022-09-28 06:01 UTC, Dr-TSNG requested changes

2022-09-28 06:01 UTC, Dr-TSNG commented on .github/workflows/main.yml
> +      run: python 每日上报.py
咋多了几个空格（

2022-09-28 06:22 UTC, 0x401000Nu1l commented on .github/workflows/main.yml
> +      run: python 每日上报.py
失误。sry

2023-02-23 09:59 UTC, closed without merging